= アーキテクチャ
:revdate: 2025-07-23
:page-revdate: {revdate}

{product_name}には2つの主要なコンポーネントがあります。{product_name}コントローラとクラスタエージェントです。これらのコンポーネントは、2段階のプルモデルで機能します。{product_name}コントローラはgitからプルし、クラスタエージェントは{product_name}コントローラからプルします。

== {product_name}コントローラ

{product_name}コントローラは、標準的なKubernetesクラスタで実行されるKubernetesコントローラのセットです。 {product_name}コントローラによって公開される唯一のAPIはKubernetes APIであり、フリートコントローラ用のカスタムAPIはありません。

== クラスタエージェント

1つのクラスタエージェントが各クラスタで実行され、{product_name}コントローラと通信する責任があります。
クラスタから{product_name}コントローラへの唯一の通信はこのエージェントによって行われ、すべての通信は管理されたクラスタから{product_name}コントローラに向かいます。フリートコントローラは、ダウンストリームのクラスタへの接続を開始しません。これは、管理されたクラスタがプライベートネットワークやNATの背後で実行できることを意味します。唯一の要件は、クラスタエージェントが{product_name}コントローラを実行しているクラスタのKubernetes APIと通信できる必要があることです。これに対する唯一の例外は、xref:how-tos-for-operators/cluster-registration.adoc#_manager_initiated[マネージャー主導の登録]クラスタ登録フローを使用する場合です。これは必須ではありませんが、オプションのパターンです。

クラスタエージェントは「always-on」接続であるとは想定されていません。接続できるようになるとすぐに動作を再開します。今後の機能拡張により、エージェントがチェックインする時刻をスケジュールする機能が追加される可能性がありますが、現時点では常に接続を試みます。

== セキュリティ

{product_name}コントローラは動的にサービスアカウントを作成し、それらのRBACを管理し、トークンをダウンストリームのクラスタに渡します。クラスタは、オプションでクラスタ登録トークンを期限切れにすることにより登録されます。
クラスタ登録トークンは、登録プロセス中にのみ使用され、そのクラスタに特有の資格情報を生成します。クラスタ資格情報が確立されると、クラスタはクラスタ登録トークンを「忘れます」。

クラスタに与えられたサービスアカウントには、そのクラスタに対して特別に作成されたネームスペースに`BundleDeployment`を一覧表示する特権のみがあります。それはまた、`status`の`BundleDeployment`サブリソースと、その`status`リソースの`Cluster`サブリソースを更新することもできます。

== コンポーネントの概要

コンポーネントの概要と、それらが高レベルでどのように相互作用するかについて。

image::FleetComponents.svg[スタティック, 600]
