= バンドルライフサイクル
:revdate: 2025-07-23
:page-revdate: {revdate}

バンドルは、gitからリソースをオーケストレーションするために使用される内部リソースです。GitRepoがスキャンされると、1つ以上のバンドルが生成されます。

{product_name}バンドルのライフサイクルを示すために、 https://github.com/rancher/fleet-examples/tree/master/multi-cluster/helm[multi-cluster/helm]をケーススタディとして使用します。

. ユーザーは、multi-cluster/helmリポジトリを指すxref:how-tos-for-users/gitrepo-add.adoc#_create_gitrepo_instance[GitRepo]を作成します。
. `gitjob-controller`はGitRepoから変更を同期し、ポーリングまたはxref:how-tos-for-users/webhook.adoc[webhook event]からの変更を検出します。すべてのコミット変更に対して、`gitjob-controller`はgitリポジトリをクローンし、`fleet.yaml`やその他のマニフェストなどのリポジトリからコンテンツを読み取り、{product_name}xref:reference/ref-status-fields.adoc#_bundles[バンドル]を作成するジョブを生成します。
+
[NOTE]
====
イメージ名`rancher/tekton-utils`を持つジョブポッドは、GitRepoと同じネームスペースに配置されます。
====
+
. その後、`fleet-controller`はバンドルから変更を同期します。ターゲットに応じて、`fleet-controller`はバンドルとターゲットクラスターの組み合わせである`BundleDeployment`リソースを作成します。
. その後、`fleet-agent`は{product_name}コントロールプレーンから`BundleDeployment`を取得します。エージェントは、`BundleDeployment`からダウンストリームクラスターへの https://helm.sh/docs/intro/install/[Helmチャート]としてバンドルマニフェストをデプロイします。
. `fleet-agent`はアプリケーションバンドルを監視し、次の順序でステータスを報告し続けます: +bundledeployment+ > ++バンドル++ > +GitRepo+ > ++クラスター++。

この図は、バンドルがデプロイされるまでに通過するさまざまなレンダリングステージを示しています。

image::FleetBundleStages.svg[バンドルステージ]

[[examining-the-bundle-lifecycle-with-the-cli]]
== CLIを使用したバンドルライフサイクルの検証

いくつかのFleet CLIコマンドが、バンドルのデバッグに役立ちます。

image::fleetCLI-key-components.svg[Fleet CLIの主要コマンドの動作を説明する図]

=== fleet apply

xref:reference/cli/fleet-cli/fleet_apply.adoc[Apply]は、Helmチャート、マニフェスト、またはKustomizeフォルダーなどのKubernetesリソースを含むフォルダーを{product_name}バンドルリソースにレンダリングします。

----
git clone https://github.com/rancher/fleet-test-data
cd fleet-test-data
fleet apply -n fleet-local -o bundle.yaml testbundle simple-chart/
----

`fleet apply`を使用してバンドルを作成する方法に関する詳細情報は、xref:how-tos-for-users/bundle-add.adoc[バンドルに関するセクション]で見つけることができます。

[[fleet-target]]
=== fleet target

xref:reference/cli/fleet-cli/fleet_target.adoc[Target]はファイルからバンドルを読み込み、ライブクラスターと連携して`bundledeployment`および`content`リソースを出力します。これはFleetコントローラーが作成するものです。ネームスペースを引数として受け取るため、例えばクラスターリソースをそのネームスペース内で探すことができます。"ターゲティング"中に使用されるデータ構造をダンプすることもできるため、ラベルやクラスター名に関して取られた決定を確認できます。

=== フリートデプロイ

xref:reference/cli/fleet-cli/fleet_deploy.adoc[デプロイ]は`fleet target`の出力、またはダンプされたバンドルデプロイメント/コンテンツリソースを受け取り、それをクラスターにデプロイします。これはFleet agentが行うことと同様です。ドライランモードでは、helmを使ってインストールするのではなく、生成されるリソースを出力します。コマンドは入力リソースを作成しないため、実行中のFleet agentがデプロイメントをガーベジコレクトする可能性があります。

デプロイコマンドは、エアギャップ(された)クラスターにバンドルを持ち込むために使用できます。

=== ライフサイクルCLI

Fleet CLIコマンドは、バンドルライフサイクルのデバッグと理解を助けます。以下の例は、CLIを使用した完全なバンドルライフサイクルを示しています：

[source,bash]
----
git clone https://github.com/rancher/fleet-test-data
cd fleet-test-data
fleet apply -n fleet-local -o bundle.yaml testbundle simple-chart/
fleet target --bundle-file bundle.yaml --list-inputs  > bd.yaml
fleet deploy --input-file bd.yaml --dry-run
----

applyに関する情報は、xref:how-tos-for-users/bundle-add.adoc[バンドルリソースの作成]を参照してください。

