version: 2

updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    target-branch: "product-docs"
    schedule:
      interval: "daily"
