= How to enable experimental features
:revdate: 2025-10-10
:page-revdate: {revdate}

{product_name} supports experimental features that are disabled by default and can be enabled by the user.

Enabling or disabling experimental features is done using extra environment variables that are available when deploying `rancher/fleet`.

For more information, refer to Configure xref:reference/ref-configuration.adoc#_configure-product-name-install-options-in-rancher[{product_name} install options in Rancher]

[#_available-experimental-features]
== Available experimental features

{product_name} currently supports the following experimental features, toggled through their respective environment variables:

* xref:experimental-features/scheduling.adoc[Scheduling]: `EXPERIMENTAL_SCHEDULES`
* xref:experimental-features/experimental-downstream-resource.adoc[Automated propagation of resources to downstream
  clusters]: `EXPERIMENTAL_COPY_RESOURCES_DOWNSTREAM`

[#_enabling-an-experimental-feature]
== Enabling an experimental feature

[#_enabling-when-installing-product-name-stand-alone]
=== Enabling when installing {product_name} stand-alone

All you need to do is pass something like:

[source,bash]
----
--set-string extraEnv[0].name=EXPERIMENTAL_SCHEDULES \
--set-string extraEnv[0].value=true
----

to your `helm install` or `helm upgrade` command.

[NOTE]
====
You have to use `--set-string` because otherwise the boolean value won't work as expected.
====

[#_enabling-when-installing-product-name-with-rancher]
=== Enabling when installing {product_name} with Rancher

You can also activate the experimental features in {product_name} when installing Rancher.

The parameters are the same, but you have to add the `fleet.` prefix:

[source,bash]
----
--set-string fleet.extraEnv[0].name=EXPERIMENTAL_SCHEDULES \
--set-string fleet.extraEnv[0].value=true
----
