= fleet dump
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-02-05
:page-revdate: {revdate}

Déposer les données du cluster dans une archive.

[#_overview]
== Présentation

Déposer les données d'un cluster dans une archive, y compris{nbsp}: +
* {product_name} ressources gérées +
* événements Kubernetes +
* Métriques exposées par les contrôleurs Fleet

[source,text]
----
fleet dump <flags>
----

[#_flags]
== Drapeaux

[source,text]
----
  -p <path>         Path to the archive file to generate
----

[#_output]
== Sortie

[#_contents]
=== Table des matières

La commande `dump` produit une archive `.tgz` contenant les données suivantes{nbsp}:

* Ressources brutes de Fleet, au format YAML{nbsp}:
** Ensembles
** BundleDeployments
** BundleNamespaceMappings
** Clusters
** ClusterGroups
** GitRepos
** GitRepoRestrictions
** HelmOps

* Événements Kubernetes pour les espaces de noms suivants{nbsp}:
** `cattle-fleet-system`
** `cattle-fleet-local-system`
** `default`
** `kube-system`
** chaque espace de noms contenant une ressource Fleet `Cluster`

* Métriques exposées par les services `monitoring-*` vivant dans l'espace de noms `cattle-fleet-system`.
Cela inclut généralement les services `monitoring-gitjob` et `monitoring-fleet-controller`, ainsi que leurs +
xref:how-tos-for-operators/installation.adoc#_multi_controller_installation_sharding[shardés] homologues, le cas échéant.

[#_format]
==== Format

Les ressources brutes {product_name} sont chacune stockées dans un fichier différent, nommé `<kind>_<namespace>_<name>`, où `<kind>` est l'un des noms de ressources brutes mentionnés dans la section précédente, en minuscules.

Les événements Kubernetes sont répartis dans des fichiers par espace de noms, chaque fichier étant nommé `events_<namespace>`.
Ils contiennent un événement par ligne, chaque événement étant encodé en JSON.

Les métriques sont stockées dans des fichiers par service, chaque fichier étant nommé `metrics_<service_name>`.
Leurs contenus sont `GET` corps de réponse reçus du point de terminaison `/metrics` de chaque service, tels quels.

[#_see_also]
== VOIR ÉGALEMENT

* xref:/reference/cli/fleet-cli/fleet.adoc[{product_name}]
* xref:/reference/cli/fleet-cli/fleet_monitor.adoc[fleet monitor]
