== fleet dump
:revdate: 2026-02-05
:page-revdate: {revdate}

Dump cluster data into an archive.

== Overview

Dump data from a cluster into an archive, including:
* Fleet-managed resources
* Kubernetes events
* Metrics exposed by Fleet controllers

[source,text]
----
fleet dump <flags>
[source,text]
----

=== Flags

[source,text]
----
  -p <path>         Path to the archive file to generate
[source,text]
----

=== Output

==== Contents

The `dump` command produces a `.tgz` archive containing the following data:
* Raw Fleet resources, in YAML format:
    * Bundles
    * BundleDeployments
    * BundleNamespaceMappings
    * Clusters
    * ClusterGroups
    * GitRepos
    * GitRepoRestrictions
    * HelmOps
* Kubernetes events for the following namespaces:
    * `cattle-fleet-system`
    * `cattle-fleet-local-system`
    * `default`
    * `kube-system`
    * each namespace containing a Fleet `Cluster` resource
* Metrics exposed by `monitoring-*` services living in the `cattle-fleet-system` namespace.
This typically includes `monitoring-gitjob` and `monitoring-fleet-controller` services, as well as their
xref:how-tos-for-operators/installation.adoc#multi-controller-install-sharding[sharded] counterparts, if any.

==== Format

Raw Fleet resources are each stored in a different file, named as `<kind>_<namespace>_<name>`, where `<kind>` is
one of the raw resource names mentioned in the previous section, in lowercase.

Kubernetes events are split into files by namespace, each file named as `events_<namespace>`.
They contain one event per line, each event being encoded in JSON.

Metrics are stored into files by service, each file being named `metrics_<service_name>`.
Their contents are `GET` response bodies received from each service's `/metrics` endpoint, verbatim.

=== SEE ALSO

* xref:/reference/cli/fleet-cli/fleet.adoc[fleet]
* xref:/reference/cli/fleet-cli/fleet_monitor.adoc[fleet monitor]
