= Uninstall
:revdate: 2025-07-23
:page-revdate: {revdate}

[CAUTION]
====
Removing the CRDs will remove all deployed workloads.
====


== {product_name} Standalone

{product_name} is packaged as two Helm charts so uninstallation is accomplished by uninstalling the appropriate Helm charts.

However {product_name} uses https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/[finalizers], so uninstall workloads first to give the {product_name} controllers time to clean up.

[source,shell]
----
kubectl delete clusters.fleet.cattle.io -A
kubectl delete gitrepos -A
kubectl delete bundles -A
----

Note, it can be easier to remove the namespaces containing the workloads, e.g.:

[source,shell]
----
kubectl delete ns fleet-local
kubectl delete ns fleet-default
----

The custom resources are not uninstalled by Helm 3, remove them first:

[source,shell]
----
kubectl delete crd gitrepos.fleet.cattle.io bundles.fleet.cattle.io contents.fleet.cattle.io \
  bundledeployments.fleet.cattle.io imagescans.fleet.cattle.io \
  bundlenamespacemappings.fleet.cattle.io gitreporestrictions.fleet.cattle.io \
  clusters.fleet.cattle.io clustergroups.fleet.cattle.io \
  clusterregistrations.fleet.cattle.io clusterregistrationtokens.fleet.cattle.io
----

Then, to uninstall {product_name}, run the following commands:

[,shell]
----
helm -n cattle-fleet-system uninstall fleet
helm -n cattle-fleet-system uninstall fleet-crd
----

[NOTE]
====
If uninstall gets stuck it is likely due to finalizers. Resource status fields, e.g. on a namespace, will list the resources waiting for their finalizers to be removed. The finalizers can be removed manually with kubectl, if their controllers are no longer running.
====


Afterwards one can also remove {product_name}-related namespaces and their content:

[source,shell]
----
kubectl delete ns cattle-fleet-system
kubectl delete ns cattle-fleet-clusters-system
kubectl delete ns -l "fleet.cattle.io/managed=true"
----

== {product_name} in Rancher

{product_name} in Rancher cannot be uninstalled, without uninstalling Rancher. However, the GitOps feature can be disabled.
When disabled, the gitjob deployment is no longer deployed into the Rancher server's local cluster, and continuous-delivery is not shown in the Rancher UI.

ifeval::["{product}" == "fleet"]
More information can be found in the Rancher docs: https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/enable-experimental-features/continuous-delivery.
endif::[]

ifeval::["{product}" == "continuous-delivery"]
More information can be found in the Rancher docs: https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/experimental-features/continuous-delivery.html.
endif::[]