= Fleet anwenden
:revdate: 2026-02-05
:page-revdate: {revdate}

Erstellen Sie Bündel aus Verzeichnissen und geben Sie sie aus oder wenden Sie sie in einem Cluster an

----
fleet apply [flags] BUNDLE_NAME PATH...
----

== Optionen

----
  -b, --bundle-file string                     Location of the raw Bundle resource yaml
      --bundle-creation-max-concurrency int    Number of concurrent routines to create bundles (default 4)
      --cacerts-file string                    Path of custom cacerts for helm repo
      --commit string                          Commit to assign to the bundle
  -c, --compress                               Force all resources to be compress
      --context string                         kubeconfig context for authentication
      --correct-drift                          Rollback any change made from outside of {product_name}
      --correct-drift-force                    Use --force when correcting drift. Resources can be deleted and recreated
      --correct-drift-keep-fail-history        Keep helm history for failed rollbacks
      --debug                                  Turn on debug logging
      --debug-level int                        If debugging is enabled, set klog -v=X
      --delete-namespace                       Delete GitRepo target namespace after the GitRepo or Bundle is deleted
  -f, --file string                            Location of the fleet.yaml
      --helm-credentials-by-path-file string   Path of file containing helm credentials for paths
      --helm-repo-url-regex string             Helm credentials will be used if the helm repo matches this regex. Credentials will always be used if this is empty or not provided
  -h, --help                                   help for apply
      --keep-resources                         Keep resources created after the GitRepo or Bundle is deleted
  -k, --kubeconfig string                      kubeconfig for authentication
  -l, --label strings                          Labels to apply to created bundles
  -n, --namespace string                       namespace (default "fleet-local")
      --oci-basic-http                         Use HTTP to access the OCI regustry
      --oci-insecure                           Allow connections to OCI registry without certs
      --oci-password-file string               Path of file containing basic auth password for OCI registry
      --oci-reference string                   OCI registry reference
      --ociusername string                     Basic auth username for OCI registry
  -o, --output string                          Output contents to file or - for stdout
      --password-file string                   Path of file containing basic auth password for helm repo
      --paused                                 Create bundles in a paused state
  -a, --service-account string                 Service account to assign to bundle created
      --ssh-privatekey-file string             Path of ssh-private-key for helm repo
      --sync-generation int                    Generation number used to force sync the deployment
      --target-namespace string                Ensure this bundle goes to this target namespace
      --targets-file string                    Addition source of targets and restrictions to be append
      --username string                        Basic auth username for helm repo
      --driven-scan                            Use driven scan. Bundles are defined by the user.
                                               Paths will be defined by the tuple <base, options> separated by a separator.
                                               The default separator is the character ':'. If you need to use a different one,
                                               use the --driven-scan-sep flag.
      --driven-scan-sep                        Separator used for user-driven bundle generation paths. (default: ':')
----

=== Wissenswertes

`fleet apply` liest `known_hosts`` Daten aus einer Umgebungsvariable (`FLEET_KNOWN_HOSTS`), ähnlich wie es der Git-Kloner tut.

Das bedeutet, dass Sie, falls Sie `fleet apply` direkt auf Ihrer Hostmaschine ausführen möchten und ihm einen benutzerdefinierten Wert von `KNOWN_HOSTS` bereitstellen, `FLEET_KNOWN_HOSTS` vorher exportieren oder es als `FLEET_KNOWN_HOSTS=<your_entries> fleet apply <args>` ausführen müssen.

Die Anzahl der gleichzeitigen Bündelerstellungsroutinen kann über das `--bundle-creation-max-concurrency`-Flag oder die `FLEET_BUNDLE_CREATION_MAX_CONCURRENCY`-Umgebungsvariable konfiguriert werden. Der Standardwert ist 4. Dies kann nützlich sein, wenn Sie mit großen Repositories arbeiten, die viele Bündel enthalten, da es Ihnen ermöglicht, die Parallelität der Bündelerstellung zu steuern. Beispiel:

`FLEET_BUNDLE_CREATION_MAX_CONCURRENCY=8 fleet apply <args>`

== SIEHE AUCH
* xref:/reference/cli/fleet-cli/fleet.adoc[ {product_name}]     - Verwalten Sie {product_name} Operationen
