= Core Concepts

ifeval::["{build-type}" == "product"]
<<_suse_rancher_prime_continous_delivery,{product_name}>> is fundamentally a set of Kubernetes custom resource definitions (CRDs) and controllers to manage GitOps for a single Kubernetes cluster or a large-scale deployment of Kubernetes clusters.
endif::[]

ifeval::["{build-type}" == "community"]
<<_continous_delivery,{product_name}>> is fundamentally a set of Kubernetes custom resource definitions (CRDs) and controllers to manage GitOps for a single Kubernetes cluster or a large-scale deployment of Kubernetes clusters.
endif::[]

[IMPORTANT]
====
For more on the naming conventions of CRDs, refer xref:troubleshooting.adoc#naming-conventions-for-crds[Where to look for root causes of issues].
====

Below are some of the concepts of Fleet that will be useful throughout this documentation:

* *Fleet Manager*: The centralized component that orchestrates the deployments of Kubernetes assets
  from git. In a multi-cluster setup, this is typically be a dedicated Kubernetes cluster. In a
  single cluster setup, the Fleet manager will be running on the same cluster you are managing with GitOps.
* *Fleet controller*: The controller(s) running on the Fleet manager orchestrating GitOps. In practice,
  the Fleet manager and Fleet controllers are used fairly interchangeably.
+
ifeval::["{build-type}" == "product"]
* *Single Cluster Style*: This is a style of installing <<_suse_rancher_prime_continous_delivery,{product_name}>> in which the manager and downstream cluster are the same cluster.  This is a very simple pattern to quickly get up and running with GitOps.
* *Multi Cluster Style*: This is a style of running <<_suse_rancher_prime_continous_delivery,{product_name}>> in which you have a central manager that manages a large
  number of downstream clusters.
* *Fleet agent*: Every managed downstream cluster will run an agent that communicates back to the Fleet manager. This agent is just another set of Kubernetes controllers running in the downstream cluster.
* *GitRepo*: Git repositories that are watched by <<_suse_rancher_prime_continous_delivery,{product_name}>> are represented by the type `GitRepo`.
endif::[]
+
ifeval::["{build-type}" == "community"]
* *Single Cluster Style*: This is a style of installing <<_continous_delivery,{product_name}>> in which the manager and downstream cluster are the same cluster.  This is a very simple pattern to quickly get up and running with GitOps.
* *Multi Cluster Style*: This is a style of running <<_continous_delivery,{product_name}>> in which you have a central manager that manages a large
  number of downstream clusters.
* *Fleet agent*: Every managed downstream cluster run an agent that communicates back to the Fleet manager. This agent is just another set of Kubernetes controllers running in the downstream cluster.
* *GitRepo*: Git repositories that are watched by <<_continous_delivery,{product_name}>> are represented by the type `GitRepo`.
endif::[]

____
*Example installation order via `GitRepo` custom resources when using Fleet for the configuration management of downstream clusters:*

. Install https://github.com/projectcalico/calico[Calico] CRDs and controllers.
. Set one or multiple cluster-level global network policies.
. Install https://github.com/open-policy-agent/gatekeeper[GateKeeper]. Note that *cluster labels* and *overlays* are critical features, as they determine which clusters will get each part of the bundle.
. Set up and configure ingress and system daemons.
____

ifeval::["{build-type}" == "product"]
* *Single Cluster Style*: This is a style of installing <<_suse_rancher_prime_continous_delivery,{product_name}>> in which the manager and downstream cluster are the same cluster.  This is a very simple pattern to quickly get up and running with GitOps.
* *Bundle*: An internal unit used for the orchestration of resources from git.
  When a `GitRepo` is scanned it will produce one or more bundles. Bundles are a collection of
  resources that get deployed to a cluster. `Bundle` is the fundamental deployment unit used in <<_suse_rancher_prime_continous_delivery,{product_name}>>. The
  contents of a `Bundle` may be Kubernetes manifests, Kustomize configuration, or Helm charts.
  Regardless of the source the contents are dynamically rendered into a Helm chart by the agent
  and installed into the downstream cluster as a helm release.
 ** To see the *life cycle of a bundle*, click xref:./ref-bundle-stages.adoc[here].
* *BundleDeployment*: When a `Bundle` is deployed to a cluster an instance of a `Bundle` is called a `BundleDeployment`.
  A `BundleDeployment` represents the state of that `Bundle` on a specific cluster with its cluster specific
  customizations. The Fleet agent is only aware of `BundleDeployment` resources that are created for
  the cluster the agent is managing.
 ** For an example of how to deploy Kubernetes manifests across clusters using <<_suse_rancher_prime_continous_delivery,{product_name}>> customization, click xref:gitrepo-targets.adoc#customization-per-cluster[here].
* *Downstream Cluster*: Clusters to which <<_suse_rancher_prime_continous_delivery,{product_name}>>  deploys manifests are referred to as downstream clusters. In the single cluster use case, the Fleet manager Kubernetes cluster is both the manager and downstream cluster at the same time.
* *Cluster Registration Token*: Tokens used by agents to register a new cluster.
endif::[]
+
ifeval::["{build-type}" == "community"]
* *Bundle*: An internal unit used for the orchestration of resources from git.
  When a `GitRepo` is scanned it will produce one or more bundles. Bundles are a collection of
  resources that get deployed to a cluster. `Bundle` is the fundamental deployment unit used in <<_continous_delivery,{product_name}>> . The
  contents of a `Bundle` may be Kubernetes manifests, Kustomize configuration, or Helm charts.
  Regardless of the source the contents are dynamically rendered into a Helm chart by the agent
  and installed into the downstream cluster as a helm release.
 ** To see the *life cycle of a bundle*, click xref:ref-bundle-stages.adoc[here].
* *BundleDeployment*: When a `Bundle` is deployed to a cluster an instance of a `Bundle` is called a `BundleDeployment`.
  A `BundleDeployment` represents the state of that `Bundle` on a specific cluster with its cluster specific
  customizations. The Fleet agent is only aware of `BundleDeployment` resources that are created for
  the cluster the agent is managing.
 ** For an example of how to deploy Kubernetes manifests across clusters using <<_continous_delivery,{product_name}>>  customization, click xref:gitrepo-targets.adoc#customization-per-cluster[here].
* *Downstream Cluster*: Clusters to which <<_continous_delivery,{product_name}>>  deploys manifests are referred to as downstream clusters. In the single cluster use case, the Fleet manager Kubernetes cluster is both the manager and downstream cluster at the same time.
* *Cluster Registration Token*: Tokens used by agents to register a new cluster.
endif::[]
