= Glossary

== Agent

ifeval::["{build-type}" == "product"]
In <<_suse_rancher_prime_continous_delivery,{product_name}>>'s context, an agent is a Kubernetes deployment responsible for deploying workloads to its cluster.
endif::[]

ifeval::["{build-type}" == "community"]
In <<_continous_delivery,{product_name}>>'s context, an agent is a Kubernetes deployment responsible for deploying workloads to its cluster.
endif::[]

This entails monitoring a specific namespace on the upstream cluster, and deploying any bundle deployments, living in that namespace, to the downstream cluster where the agent lives.

== Bundle

ifeval::["{build-type}" == "product"]
A bundle is a <<_suse_rancher_prime_continous_delivery,{product_name}>>-specific resource (also known as a https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[Custom Resource] in Kubernetes) representing a workload, or set of user resources, to be deployed. It is typically generated by <<_suse_rancher_prime_continous_delivery,{product_name}>> from a path of a git repository.
endif::[]

ifeval::["{build-type}" == "community"]
A bundle is a <<_continous_delivery,{product_name}>>-specific resource (also known as a https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[Custom Resource] in Kubernetes) representing a workload, or set of user resources, to be deployed. It is typically generated by <<_continous_delivery,{product_name}>> from a path of a git repository.
endif::[]

== Chart

See https://helm.sh/docs/topics/charts/[this definition] of a Helm chart.

== Cluster

A cluster refers to:

ifeval::["{build-type}" == "product"]
* a https://kubernetes.io/docs/concepts/architecture/[Kubernetes cluster] managed by <<_suse_rancher_prime_continous_delivery,{product_name}>>.
* a `Cluster` https://github.com/rancher/fleet/blob/main/pkg/apis/fleet.cattle.io/v1alpha1/cluster_types.go#L59[resource] in Fleet's API, which <<_suse_rancher_prime_continous_delivery,{product_name}>> uses to manage that Kubernetes cluster.
endif::[]

ifeval::["{build-type}" == "community"]

* a https://kubernetes.io/docs/concepts/architecture/[Kubernetes cluster] managed by <<_continous_delivery,{product_name}>>.
* a `Cluster` https://github.com/rancher/fleet/blob/main/pkg/apis/fleet.cattle.io/v1alpha1/cluster_types.go#L59[resource] in Fleet's API, which <<_continous_delivery,{product_name}>> uses to manage that Kubernetes cluster.
endif::[]

== Continuous Delivery/Deployment

Definitions and distinctions between Continuous _Delivery_ and Continuous _Deployment_ greatly vary, for instance
depending on:

* whether the deployment step is included in the process, and to which environment: production or other?
* what triggers a deployment: is it a manual or automated step?

This much is clear, the goal is to make it easier to automate deployments.

== Custom Resource

See https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[this official definition].
In short, a custom resource is a resource defined for the purposes of an application, to extend the set of resources supported by the Kubernetes API (pods, deployments, services, etc).

== Custom Resource Definition

See https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#customresourcedefinitions[this explanation] from the Kubernetes docs.

== Deployment

A deployment may refer to:


ifeval::["{build-type}" == "product"]
* a https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/[Kubernetes deployment],
whether part of a user workload or part of <<_suse_rancher_prime_continous_delivery,{product_name}>> itself, such as an agent deployment, controller deployments.
* the action of deploying a user workload, which means <<_suse_rancher_prime_continous_delivery,{product_name}>> reading configuration (`GitRepo`, `fleet.yaml`, etc) and, as a result, creating resources on target clusters.
endif::[]

ifeval::["{build-type}" == "community"]
* a https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/[Kubernetes deployment],
whether part of a user workload or part of <<_continous_delivery,{product_name}>> itself, such as an agent deployment, controller deployments.
* the action of deploying a user workload, which means <<_continous_delivery,{product_name}>> reading configuration (`GitRepo`, `fleet.yaml`, etc) and, as a result, creating resources on target clusters.
endif::[]

== Downstream Cluster

ifeval::["{build-type}" == "product"]
A downstream cluster is a Kubernetes cluster where user workloads will run, without any <<_suse_rancher_prime_continous_delivery,{product_name}>> controllers living there. It is a target cluster for <<_suse_rancher_prime_continous_delivery,{product_name}>>, where only a <<_suse_rancher_prime_continous_delivery,{product_name}>> agent lives beside user workloads.
endif::[]

ifeval::["{build-type}" == "community"]
A downstream cluster is a Kubernetes cluster where user workloads will run, without any <<_continous_delivery,{product_name}>> controllers living there. It is a target cluster for <<_continous_delivery,{product_name}>>, where only a <<_continous_delivery,{product_name}>> agent lives beside user workloads.
endif::[]

== fleet.yaml

A `fleet.yaml` file lives in a git repository and stores options for a bundle and bundle deployments to be generated from that bundle. More information is available xref:ref-fleet-yaml.adoc[Fleet.yaml documentation].

== GitOps

GitOps refers to git-triggered operations, where git is the source of truth and changes to a git repository lead to
changes being applied to the state of one or more clusters.

== GitRepo

ifeval::["{build-type}" == "product"]
A `GitRepo` is a <<_suse_rancher_prime_continous_delivery,{product_name}>>-specific resource, to be used as an entry point to using <<_suse_rancher_prime_continous_delivery,{product_name}>>.
Creating a `GitRepo` pointing to a set of paths in a git repository enables <<_suse_rancher_prime_continous_delivery,{product_name}>> to monitor those paths and deploy resources stored or referenced there.
endif::[]

ifeval::["{build-type}" == "community"]
A `GitRepo` is a <<_continous_delivery,{product_name}>>-specific resource, to be used as an entry point to using <<_continous_delivery,{product_name}>>.
Creating a `GitRepo` pointing to a set of paths in a git repository enables <<_continous_delivery,{product_name}>> to monitor those paths and deploy resources stored or referenced there.
endif::[]

== Label

Refers to a https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[Kubernetes label].

== Multi-Cluster

A multi-cluster setup involves more than one cluster: the upstream cluster, needed to manage deployment of workloads, and at least one downstream cluster.

== Namespace

Refers to a https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/[Kubernetes namespace].

== Reconcile

Reconciling is used in the context of states in Kubernetes clusters. Reconciling a resource means updating it so that its _actual_ state matches its _expected_ state, be it from configuration, eg. from a git repository, chart, etc.

When using GitOps, updates to a git repository may translate into new expected states for resources configured through that git repository. As a result, affected resources will be reconciled.
A resource's state may also depend on another resource, leading to additional reconciliation. For instance, a cluster group's status depends on statuses of individual clusters contained in that cluster group. Therefore, a change in a cluster's state will result in any cluster group(s) to which that cluster belongs to being reconciled as well.

== Registration

Cluster registration is the process of getting a Fleet agent, living in a downstream cluster, recognised by Fleet controllers in the upstream cluster.

ifeval::["{build-type}" == "product"]
Once registration is complete for a downstream cluster, <<_suse_rancher_prime_continous_delivery,{product_name}>> is able to deploy workloads to that cluster.
endif::[]

ifeval::["{build-type}" == "community"]
Once registration is complete for a downstream cluster, <<_continous_delivery,{product_name}>> is able to deploy workloads to that cluster.
endif::[]

== Repository

A repository may be:

ifeval::["{build-type}" == "product"]
* a git repository, storing code, configuration or any kind of files and keeping track of changes made to those files
through commits. <<_suse_rancher_prime_continous_delivery,{product_name}>> can monitor a git repository for new commits pushed to a specific branch or revision, at one or more paths, through xref:gitrepo-add.adoc[GitRepo] resources.
* a Helm repository, hosting Helm charts and an index file referencing them. <<_suse_rancher_prime_continous_delivery,{product_name}>> is able to install Helm charts andapply user-defined configuration to them.
endif::[]

ifeval::["{build-type}" == "community"]
* a git repository, storing code, configuration or any kind of files and keeping track of changes made to those files
through commits. <<_continous_delivery,{product_name}>> can monitor a git repository for new commits pushed to a specific branch or revision, at one or more paths, through xref:gitrepo-add.adoc[GitRepo] resources.
* a Helm repository, hosting Helm charts and an index file referencing them. <<_continous_delivery,{product_name}>> is able to install Helm charts andapply user-defined configuration to them.
endif::[]

== Resources

This usually refers to Kubernetes resources, which may be:

* core resources defined by Kubernetes itself, such as config maps, deployments, pods, services, etc
+
ifeval::["{build-type}" == "product"]
* custom resources defined by individual applications, such as <<_suse_rancher_prime_continous_delivery,{product_name}>> itself, which defines `GitRepo`, `Bundle`, `Bundledeployment` and a few others.
endif::[]
+
ifeval::["{build-type}" == "community"]
* custom resources defined by individual applications, such as <<_continous_delivery,{product_name}>> itself, which defines `GitRepo`, `Bundle`, `Bundledeployment` and a few others.
endif::[]

== Target

ifeval::["{build-type}" == "product"]
<<_suse_rancher_prime_continous_delivery,{product_name}>> uses this word in the context of determining where a workload will run. This represents a _destination_ cluster for a workload.
endif::[]

ifeval::["{build-type}" == "community"]
<<_continous_delivery,{product_name}>> uses this word in the context of determining where a workload will run. This represents a _destination_ cluster for a workload.
endif::[]

== Upstream Cluster

A Kubernetes cluster where Fleet controllers run. This is the cluster where ``GitRepo``s, bundles and bundle deployments are created.
Also called _management_ cluster.

== Workload

ifeval::["{build-type}" == "product"]
A workload represents what users want to deploy through <<_suse_rancher_prime_continous_delivery,{product_name}>>. It may be a set of Helm charts, Kubernetes manifests, kustomize, etc, stored or referenced in a git repository.

When a user creates a `GitRepo` resource pointing to that git repository, and subsequently when relevant changes are found in that repository, <<_suse_rancher_prime_continous_delivery,{product_name}>> deploys workloads.
endif::[]

ifeval::["{build-type}" == "community"]
A workload represents what users want to deploy through <<_continous_delivery,{product_name}>>. It may be a set of Helm charts, Kubernetes manifests, kustomize, etc, stored or referenced in a git repository.

When a user creates a `GitRepo` resource pointing to that git repository, and subsequently when relevant changes are found in that repository, <<_continous_delivery,{product_name}>> deploys workloads.
endif::[]
