= Observability

== Status Fields

ifeval::["{build-type}" == "product"]
<<_suse_rancher_prime_continous_delivery,{product_name}>> reports most information via status fields on its custom resources. These fields are also used by the Rancher UI to display information about the state of the resources.
endif::[]

ifeval::["{build-type}" == "community"]
<<_continous_delivery,{product_name}>> reports most information via status fields on its custom resources. These fields are also used by the Rancher UI to display information about the state of the resources.
endif::[] 

See xref:ref-status-fields.adoc[status fields reference] for more information on status fields and conditions.

== K8S Events

ifeval::["{build-type}" == "product"]
<<_suse_rancher_prime_continous_delivery,{product_name}>> generates k8s events a user can subscribe to. This is the list of events:
endif::[]

ifeval::["{build-type}" == "community"]
<<_continous_delivery,{product_name}>> generates k8s events a user can subscribe to. This is the list of events:
endif::[] 

* `Created `- a new git cloning job was created
* `GotNewCommit `- a git repository has a new commit
* `JobDeleted `- a successful git cloning job is removed
* `FailedValidatingSecret `- a git cloning job cannot be created, because a required secret is missing
* `FailedToApplyRestrictions `- the GitRepo resource violates the GitRepoRestriction resource's rules
* `FailedToCheckCommit `- cannot get latest commit from the git server
* `FailedToGetGitJob `- cannot retrieve information from the git cloning job
* `Failed `- polling is disabled, triggered via webhook, but cannot get latest commit from the git server

== Metrics

ifeval::["{build-type}" == "product"]
<<_suse_rancher_prime_continous_delivery,{product_name}>> publishes prometheus metrics. They can be retrieved from these services:
endif::[]

ifeval::["{build-type}" == "community"]
<<_continous_delivery,{product_name}>> publishes prometheus metrics. They can be retrieved from these services:
endif::[] 

* `monitoring-fleet-controller.cattle-fleet-system.svc.cluster.local:8080/metrics`
* `monitoring-gitjob.cattle-fleet-system.svc.cluster.local:8081/metrics`

The https://book.kubebuilder.io/reference/metrics-reference[collection of exported metrics] includes all the information from controller-runtime, like the number of reconciled resources, the number of errors, and the time it took to reconcile.

ifeval::["{build-type}" == "product"]
When the <<_suse_rancher_prime_continous_delivery,{product_name}>> is used by Rancher and the `rancher-monitoring` chart is installed, Prometheus is automatically configured to scrape the <<_suse_rancher_prime_continous_delivery,{product_name}>> metrics.

*_NOTE_* Depending on how many resources are handled by <<_suse_rancher_prime_continous_delivery,{product_name}>>, metrics may
cause performance issues. If you have a lot of resources, you may want to disable metrics. You can do this by setting `metrics.enabled` in the `values.yaml` file to `false` when installing <<_suse_rancher_prime_continous_delivery,{product_name}>>.
endif::[]

ifeval::["{build-type}" == "community"]
When the <<_continous_delivery,{product_name}>> is used by Rancher and the `rancher-monitoring` chart is installed, Prometheus is automatically configured to scrape the <<_continous_delivery,{product_name}>> metrics.

*_NOTE_* Depending on how many resources are handled by <<_continous_delivery,{product_name}>>, metrics may
cause performance issues. If you have a lot of resources, you may want to disable metrics. You can do this by setting `metrics.enabled` in the `values.yaml` file to `false` when installing <<_continous_delivery,{product_name}>>.
endif::[] 

=== Grafana

When using Grafana and Prometheus, e.g. from https://github.com/prometheus-community/helm-charts, some setup is needed to access metrics.

ifeval::["{build-type}" == "product"]
. Create a `ServiceMonitor` resource to scrape <<_suse_rancher_prime_continous_delivery,{product_name}>> metrics. Here is an example:
endif::[] 

ifeval::["{build-type}" == "community"]
. Create a `ServiceMonitor` resource to scrape <<_continous_delivery,{product_name}>> metrics. Here is an example:
endif::[] 

[,yaml]
----
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  # Create this in the same namespace as your application
  namespace: cattle-fleet-system
  name: fleet-controller-monitor
  labels:
    # This label makes the ServiceMonitor discoverable by the Prometheus Operator
    release: monitoring  # <-- ADD THIS LABEL!
spec:
  selector:
    matchLabels:
      # This label must exist on the service you want to scrape
      app: fleet-controller # Assumed label, verify this
  namespaceSelector:
    matchNames:
      # We are only looking for the service in its own namespace
      - cattle-fleet-system
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
----

[,yaml]
----
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  # Create this in the same namespace as your application
  namespace: cattle-fleet-system
  name: fleet-gitjob-monitor
  labels:
    # This label makes the ServiceMonitor discoverable by the Prometheus Operator
    release: monitoring  # <-- ADD THIS LABEL!
spec:
  selector:
    matchLabels:
      # This label must exist on the service you want to scrape
      app: gitjob
  namespaceSelector:
    matchNames:
      # We are only looking for the service in its own namespace
      - cattle-fleet-system
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
----

ifeval::["{build-type}" == "product"]
And create it in <<_suse_rancher_prime_continous_delivery,{product_name}>>'s namespace, e.g. `cattle-fleet-system`: `kubectl create -f servicemonitor.yaml -n cattle-fleet-system`
endif::[] 

ifeval::["{build-type}" == "community"]
And create it in <<_continous_delivery,{product_name}>>'s namespace, e.g. `cattle-fleet-system`: `kubectl create -f servicemonitor.yaml -n cattle-fleet-system`

endif::[] 


. Build the Grafana dashboards and import them into Grafana. You can find the dashboards in the https://github.com/rancher/fleet-dashboards[fleet-dashboard repository]. Follow the README to build them.
