= Architecture
:revdate: 2025-04-30
:page-revdate: {revdate}

{product_name} has two primary components. The {product_name} controller and the cluster agents. These
components work in a two-stage pull model. The {product_name} controller will pull from git and the
cluster agents will pull from the {product_name} controller.

== {product_name} Controller

The {product_name} controller is a set of Kubernetes controllers running in any standard Kubernetes
cluster.  The only API exposed by the {product_name} controller is the Kubernetes API, there is no
custom API for the fleet controller.

== Cluster Agents

One cluster agent runs in each cluster and is responsible for talking to the {product_name} controller.
The only communication from cluster to {product_name} controller is by this agent and all communication
goes from the managed cluster to the {product_name} controller. The fleet controller does not initiate
connections to downstream clusters. This means managed clusters can run in private networks and behind
NATs. The only requirement is the cluster agent needs to be able to communicate with the
Kubernetes API of the cluster running the {product_name} controller. The one exception to this is if you use
the xref:how-tos-for-operators/cluster-registration.adoc#_manager_initiated[manager initiated] cluster registration flow. This is not required, but
an optional pattern.

The cluster agents are not assumed to have an "always on" connection. They will resume operation as
soon as they can connect. Future enhancements will probably add the ability to schedule times of when
the agent checks in, as it stands right now they will always attempt to connect.

== Security

The {product_name} controller dynamically creates service accounts, manages their RBAC and then gives the
tokens to the downstream clusters. Clusters are registered by optionally expiring cluster registration tokens.
The cluster registration token is used only during the registration process to generate a credential specific
to that cluster. After the cluster credential is established the cluster "forgets" the cluster registration
 token.

The service accounts given to the clusters only have privileges to list `BundleDeployment` in the namespace created
specifically for that cluster. It can also update the `status` subresource of `BundleDeployment` and the `status`
subresource of it's `Cluster` resource.

== Component Overview

An overview of the components and how they interact on a high level.

image::FleetComponents.svg[Static, 600]
