= How to enable experimental features
:revdate: 2025-04-30
:page-revdate: {revdate}

{product_name} supports experimental features that are disabled by default and that can be enabled by the user.

Enabling/disabling experimental features is done using extra environment variables that are available when deploying `rancher/fleet`.

== Enabling an experimental feature

Currently, {product_name} has OCI storage as an experimental feature.

=== Enabling when installing {product_name} stand-alone

When installing {product_name}, pass something similar to the following to your helm install or update command:

[,bash]
----
--set-string extraEnv[0].name=EXPERIMENTAL_OCI_STORAGE \
--set-string extraEnv[0].value=true \
----


Please note you have to use `--set-string` because otherwise the boolean value won't work as expected.

=== Enabling when installing {product_name} with Rancher

You can also activate the experimental features in {product_name} when installing Rancher.

The parameters are the same, but you have to add the `fleet.` prefix.

[,bash]
----
--set-string fleet.extraEnv[0].name=EXPERIMENTAL_OCI_STORAGE \
--set-string fleet.extraEnv[0].value=true \
----

== Available experimental features

Right now {product_name} supports the following experimental features:

* xref:experimental-features/oci-storage.adoc[`EXPERIMENTAL_OCI_STORAGE`]