= Conceitos Principais
:revdate: 2025-07-23
:page-revdate: {revdate}

{product_name} é fundamentalmente um conjunto de definições de recursos personalizados (CRDs) e controladores do Kubernetes para gerenciar GitOps em um único cluster Kubernetes ou uma implantação em grande escala de clusters Kubernetes.

[IMPORTANT]
====

Para mais informações sobre as convenções de nomenclatura das CRDs, clique em xref:troubleshooting.adoc#_naming_conventions_for_crds[Convenções de nomenclatura para CRDs].
====

Abaixo estão alguns dos conceitos de {product_name} que serão úteis ao longo desta documentação:

* *{product_name} Gerente*: O componente centralizado que orquestra as implantações dos ativos do Kubernetes a partir do git. Em uma configuração de múltiplos clusters, isso será tipicamente um cluster Kubernetes dedicado. Em uma configuração de cluster único, o {product_name} gerente estará rodando no mesmo cluster que você está gerenciando com GitOps.
* *{product_name} controlador*: Os controladores que estão rodando no {product_name} gerente orquestrando GitOps. Na prática, o {product_name} gerente e os {product_name} controladores são usados de forma bastante intercambiável.
* *Estilo de Cluster Único*: Este é um estilo de instalação do {product_name} em que o gerente e o cluster downstream são o mesmo cluster.  Este é um padrão muito simples para rapidamente começar a usar o GitOps.
* *Estilo de Múltiplos Clusters*: Este é um estilo de execução do {product_name} em que você tem um gerente central que gerencia um grande número de clusters downstream.
* *{product_name} agente*: Cada cluster downstream gerenciado executará um agente que se comunica de volta ao {product_name} gerente.
  Este agente é apenas mais um conjunto de controladores do Kubernetes rodando no cluster downstream.
* *GitRepo*: Repositórios Git que são monitorados pelo {product_name} são representados pelo tipo `GitRepo`.

____
*Exemplo de ordem de instalação via `GitRepo` recursos personalizados ao usar {product_name} para o gerenciamento de configuração de clusters downstream:*

. Instale https://github.com/projectcalico/calico[Calico] CRDs e controladores.
. Defina uma ou várias políticas de rede globais em nível de cluster.
. Instale https://github.com/open-policy-agent/gatekeeper[GateKeeper]. Observe que *rótulos de cluster* e *sobreposições* são recursos críticos em {product_name}, pois determinam quais clusters receberão cada parte do bundle.
. Configure e instale os daemons de ingress e do sistema.
____

* *Bundle*: Uma unidade interna usada para a orquestração de recursos do git.
  Quando um `GitRepo` é escaneado, ele produzirá um ou mais bundles. Bundles são uma coleção de recursos que são implantados em um cluster. `Bundle` é a unidade fundamental de implantação usada em {product_name}. O conteúdo de um `Bundle` pode ser manifests do Kubernetes, configuração do Kustomize ou gráficos do Helm.
  Independentemente da fonte, o conteúdo é renderizado dinamicamente em um gráfico do Helm pelo agente e instalado no cluster downstream como um release do Helm.
 ** Para ver o *ciclo de vida de um bundle*, clique em xref:explanations/ref-bundle-stages.adoc[ciclo de vida do bundle].
* *Implantação de Bundle*: Quando um `Bundle` é implantado em um cluster, uma instância de um `Bundle` é chamada de `BundleDeployment`.
  Um `BundleDeployment` representa o estado daquele `Bundle` em um cluster específico com suas personalizações específicas do cluster. O agente {product_name} está ciente apenas dos recursos `BundleDeployment` que são criados para o cluster que o agente está gerenciando.
 ** Para um exemplo de como implantar manifests do Kubernetes em clusters usando {product_name} personalização, clique em xref:how-tos-for-users/gitrepo-targets.adoc#_customization_per_cluster[personalização por cluster].
* *Cluster downstream*: Clusters para os quais {product_name} implanta manifests são chamados de clusters downstream. No caso de uso de cluster único, o cluster Kubernetes {product_name} é tanto o gerente quanto o cluster downstream ao mesmo tempo.
* *Token de Registro de Cluster*: Tokens usados por agentes para registrar um novo cluster.
